### ISSUE TITLE
Changing Search API page parameter while generating report

### ISSUE THREAD

**Issue by hepter** [cnescatlab/sonar-cnes-report#167]
#### Describe bug

This value on the server causes a timeout and some response problems. How can I reduce the value here while creating the report?

#### Screenshots & log

![image](https://user-images.githubusercontent.com/14141071/94290690-3a1c4d80-ff63-11ea-802f-5d3bdff9a839.png)

`java.lang.IllegalStateException: Fail to read response of http://aa.bb.cc.dd:9500/api/issues/search?projects=xxxxxxxxxxx&facets=types,rules,severities,directories,fileUuids,tags&ps=500&p=1&additionalFields=rules,comments&resolved=false&branch=master
	at org.sonarqube.ws.client.OkHttpResponse.fail(OkHttpResponse.java:86)
	at org.sonarqube.ws.client.OkHttpResponse.content(OkHttpResponse.java:79)
	at fr.cnes.sonar.report.providers.RequestManager.get(RequestManager.java:164)
	at fr.cnes.sonar.report.providers.AbstractDataProvider.stringRequest(AbstractDataProvider.java:346)
	at fr.cnes.sonar.report.providers.AbstractDataProvider.request(AbstractDataProvider.java:300)
	at fr.cnes.sonar.report.providers.IssuesProvider.getIssuesByStatus(IssuesProvider.java:118)
	at fr.cnes.sonar.report.providers.IssuesProvider.getIssues(IssuesProvider.java:73)
	at fr.cnes.sonar.report.factory.ReportModelFactory.create(ReportModelFactory.java:113)
	at fr.cnes.sonar.report.ReportCommandLine.execute(ReportCommandLine.java:135)
	at fr.cnes.sonar.plugin.ws.ExportTask.handle(ExportTask.java:81)
	at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:110)
	at org.sonar.server.platform.web.WebServiceFilter.doFilter(WebServiceFilter.java:88)
	at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139)
	at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:88)
	at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:72)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.CacheControlFilter.doFilter(CacheControlFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:76)
	at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:58)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.RequestIdFilter.doFilter(RequestIdFilter.java:66)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1627)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:284)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:310)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:351)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:802)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:919)
	at okio.Okio$2.read(Okio.java:138)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
	at okio.RealBufferedSource.read(RealBufferedSource.java:45)
	at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:429)
	at okio.RealBufferedSource.read(RealBufferedSource.java:45)
	at okio.RealBufferedSource.exhausted(RealBufferedSource.java:55)
	at okio.InflaterSource.refill(InflaterSource.java:101)
	at okio.InflaterSource.read(InflaterSource.java:62)
	at okio.GzipSource.read(GzipSource.java:80)
	at okio.Buffer.writeAll(Buffer.java:1004)
	at okio.RealBufferedSource.readString(RealBufferedSource.java:189)
	at okhttp3.ResponseBody.string(ResponseBody.java:174)
	at org.sonarqube.ws.client.OkHttpResponse.content(OkHttpResponse.java:77)
	... 54 common frames omitted`
#### User environment 
OS: Windows 10
Project version: 3.2.2
SonarQube: 8.4.2 (build 36762)

**Comment by begarco** [comment]
Hi @hepter,

You can change the value in https://github.com/cnescatlab/sonar-cnes-report/blob/a62f6615fb7bc3b9f5f6fb17702084312e4c4bf5/src/main/resources/requests.properties#L19

and rebuild the plugin.

Thanks.
