### ISSUE TITLE
Not able to generate report. Getting {"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}

### ISSUE THREAD

**Issue by vhaislshaha** [cnescatlab/sonar-cnes-report#189]
#### Describe the bug

Hello,

I am using SonarQube Community EditionVersion 8.5.1 (build 38104) and sonar-cnes-report-3.3.0.jar plugin.

When is Click on More > CNES Report > Select Project, Branch Key, Author > Click on Generate button

**I get following error on webpage.**

{"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}

**I see following error in SonarQube log.**

Jan 13, 2021 6:10:06 PM fr.cnes.sonar.report.ReportCommandLine execute
INFO: SonarQube URL: http://x.x.x.x:9200
Jan 13, 2021 6:10:06 PM fr.cnes.sonar.report.providers.SonarQubeInfoProvider getSonarQubeStatus
SEVERE: Not found error sent by SonarQube server (code 404, URL http://x.x.x.x:9200/api/system/status, Error <!doctype html><html lang="en"><head><title>HTTP Status 404 ? Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 ? Not Found</h1></body></html>), please check cnesreport compatibility with your SonarQube server version.
fr.cnes.sonar.report.exceptions.BadSonarQubeRequestException: Not found error sent by SonarQube server (code 404, URL http://x.x.x.x:9200/api/system/status, Error <!doctype html><html lang="en"><head><title>HTTP Status 404 ? Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 ? Not Found</h1></body></html>), please check cnesreport compatibility with your SonarQube server version.
        at fr.cnes.sonar.report.providers.RequestManager.get(RequestManager.java:172)
        at fr.cnes.sonar.report.providers.AbstractDataProvider.stringRequest(AbstractDataProvider.java:346)
        at fr.cnes.sonar.report.providers.AbstractDataProvider.request(AbstractDataProvider.java:300)
        at fr.cnes.sonar.report.providers.SonarQubeInfoProvider.getSonarQubeStatus(SonarQubeInfoProvider.java:67)
        at fr.cnes.sonar.report.factory.ServerFactory.create(ServerFactory.java:70)
        at fr.cnes.sonar.report.ReportCommandLine.execute(ReportCommandLine.java:118)
        at fr.cnes.sonar.plugin.ws.ExportTask.handle(ExportTask.java:86)
        at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:110)
        at org.sonar.server.platform.web.WebServiceFilter.doFilter(WebServiceFilter.java:88)
        at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139)
        at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:108)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:80)
        at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:67)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.platform.web.CacheControlFilter.doFilter(CacheControlFilter.java:76)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:76)
        at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:58)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.platform.web.RequestIdFilter.doFilter(RequestIdFilter.java:66)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by Sancretor** [comment]
Hi @vhaislshaha 

Thank you for your feedback !
Unfortunately, we are not compatible with SonarQube 8.5 yet. 
Please have a look at the compatibility matrix in the README.

Anyway, your problem seems to be that your web browser can't access http://x.x.x.x:9200/api/system/status.
Do you have a reverse proxy in front of SonarQube ? 
Can you access this exact URL if you enter it directly inside your web browser ?

**Comment by vhaislshaha** [comment]
Hello Sancretor,

Thank you so much for your quick response.

We do not have reverse proxy in front of SonarQube.

I tried to access http://x.x.x.x:9200/api/system/status and got HTTP Status 404 – Not Found.

Any projected date to be compatible with SonarQube 8.5?

Thanks.

**Comment by Sancretor** [comment]
Hi @vhaislshaha 

Then if you can't access this URL, you've just found the problem.
The plugin page must be able to access your SonarQube API in order to work.
Do you use the exact same URL to connect to your SonarQube server ?

Our plan is to maintain compatibility with LTS versions only.
So, as the 8.x LTS should be released in "early 2021", we should start working on this compatibility soon.

**Comment by vhaislshaha** [comment]
I use "http://x.x.x.x:9200/sonarqube" to access SonarQube.

Is the plugin page external server which trying to connect to my server? 

FYI: I forgot to mention earlier that I manually updated sonar.url in report.properties file and plugin.defaultHost & plugin.defaultPort in plugin.properties file of  sonar-cnes-report-3.3.0.jar.

============================================================================
**$ cat report.properties**

#Url of SonarQube
# sonar.url=http://x.x.x.x:9200

#Replacement character for fileseparators in NAME
report.fileseparators.replace=-
#Report filename's pattern, DATE and NAME are placeholders
report.output=BASEDIR/DATE-NAME-analysis-report.docx
#Issues' list filename's pattern DATE and NAME are placeholders
issues.output=BASEDIR/DATE-NAME-issues-report.xlsx
#Issues' list in CSV pattern, DATE and NAME are placeholders
csv.output=BASEDIR/DATE-NAME-issues-report.csv
#Issues' list in Markdown pattern, DATE and NAME are placeholders
markdown.output=BASEDIR/DATE-NAME-analysis-report.md
#Report archive filename's pattern, DATE and NAME are placeholders
zip.report.output=DATE-NAME-report.zip
#Name of the default author
report.author=default
#Default token
sonar.token=noauth
#Give the default locale
report.locale=en_US
#Name of the default output folder
report.path=.
#Name of the default template for docx
report.template=code-analysis-template.docx
#Name of the default template for xlsx
issues.template=issues-template.xlsx
#Name of metric components to exclude from report
components.excluded=Name,Path

============================================================================
**$ cat plugin.properties**

homepage.url=cnesreport/report
homepage.name=CNES Report

plugin.since=6.5
# plugin.defaultHost=http://x.x.x.x:%s
# plugin.defaultPort=9200

api.url=api/cnesreport
api.description=Export a report in zip file.

api.report.actionKey=report

api.report.args.key=key
api.report.args.description.key=Key of the project
api.report.args.branch=branch
api.report.args.description.branch=Branch of the project
api.report.args.author=author
api.report.args.description.author=Author of the report
api.report.args.token=token
api.report.args.description.token=Authentication token (for protected project)

api.tokenerror=This project can't be exported, please check your token.

**Comment by Sancretor** [comment]
Hi @vhaislshaha 

Ok, I have another guess regarding your issue...
You said that the plugin fails to reach "http://x.x.x.x:9200/api/system/status", while you are accessing SonarQube via this URL : "http://x.x.x.x:9200/sonarqube".
The only difference is the "/sonarqube" you use to access the web interface.
Then, I can only suppose that this subpath is missing inside the plugin defaultHost parameter...

Could you test if this URL works for you please ? : "http://x.x.x.x:9200/sonarqube/api/system/status"

**Comment by vhaislshaha** [comment]
I tried "http://x.x.x.x:9200/sonarqube/api/system/status" and got this...

{"id":"05E36291-AXa1UibbnEDXz8YAUJiH","version":"8.5.1.38104","status":"UP"}

**Comment by Sancretor** [comment]
Hi @vhaislshaha 

Then it means I've found your issue.
The plugin does not have this "/sonarqube" inside the URLs it uses. 
Maybe you should add it inside the plugin properties in order to have something like this : `plugin.defaultHost=http://x.x.x.x:%s/sonarqube`
Moreover, if you really don't have a reverse proxy adding the "/sonarqube", you should also change you general property which sets the SonarQube URL : `sonar.url=http://x.x.x.x:9200/sonarqube`

Could you give it a try ?

**Comment by vhaislshaha** [comment]
Looks like we passed that issue.

Now I get this error.

{"error":"This project can't be exported, please check your token."}

Any clue?

**Comment by Sancretor** [comment]
What does your SonarQube log say about it ?
I'm afraid this is the current limitation with SonarQube 8.5, as we are not compatible with it.

**Comment by vhaislshaha** [comment]
This is what I see in access.log when I try to generate report.

x.x.x.x = SonarQube server IP
y.y.y.y = my Laptop IP



x.x.x.x - - [20/Jan/2021:10:29:37 -0600] "GET /sonarqube/api/system/status HTTP/1.1" 200 76 "-" "cnesreport" "AXccL5KlPzvgX1OJAAH0"
x.x.x.x - - [20/Jan/2021:10:29:37 -0600] "GET /sonarqube/api/system/status HTTP/1.1" 200 76 "-" "cnesreport" "AXccL5KlPzvgX1OJAAH1"
x.x.x.x - - [20/Jan/2021:10:29:37 -0600] "GET /sonarqube/api/navigation/component?component=a.b.c.d:PROJ1&branch=master HTTP/1.1" 200 - "-" "cnesreport" "AXccL5KlPzvgX1OJAAH2"
x.x.x.x - - [20/Jan/2021:10:29:37 -0600] "GET /sonarqube/api/measures/component?component=a.b.c.d:PROJ1&metricKeys=ncloc,violations,ncloc_language_distribution,duplicated_lines_density,coverage,sqale_rating,reliability_rating,security_rating,alert_status,complexity,function_complexity,file_complexity,class_complexity,blocker_violations,critical_violations,major_violations,minor_violations,info_violations,new_violations,bugs,vulnerabilities,code_smells&branch=master HTTP/1.1" 200 - "-" "cnesreport" "AXccL5KlPzvgX1OJAAH3"
x.x.x.x - - [20/Jan/2021:10:29:37 -0600] "GET /sonarqube/api/measures/component_tree?component=a.b.c.d:PROJ1&metricKeys=ncloc,comment_lines_density,coverage,complexity,cognitive_complexity,duplicated_lines_density&p=1&ps=500&branch=master HTTP/1.1" 200 - "-" "cnesreport" "AXccL5KlPzvgX1OJAAH4"
x.x.x.x - - [20/Jan/2021:10:29:37 -0600] "GET /sonarqube/api/measures/component_tree?component=a.b.c.d:PROJ1&metricKeys=ncloc,comment_lines_density,coverage,complexity,cognitive_complexity,duplicated_lines_density&p=2&ps=500&branch=master HTTP/1.1" 200 - "-" "cnesreport" "AXccL5KlPzvgX1OJAAH5"
x.x.x.x - - [20/Jan/2021:10:29:37 -0600] "GET /sonarqube/api/navigation/component?component=a.b.c.d:PROJ1&branch=master HTTP/1.1" 200 - "-" "cnesreport" "AXccL5KlPzvgX1OJAAH6"
x.x.x.x - - [20/Jan/2021:10:29:37 -0600] "GET /sonarqube/api/languages/list HTTP/1.1" 200 479 "-" "cnesreport" "AXccL5KlPzvgX1OJAAH7"
x.x.x.x - - [20/Jan/2021:10:29:37 -0600] "GET /sonarqube/api/issues/search?projects=a.b.c.d:PROJ1&facets=types,rules,severities,directories,fileUuids,tags&ps=500&p=1&additionalFields=rules,comments&resolved=false&branch=master HTTP/1.1" 400 300 "-" "cnesreport" "AXccL5KlPzvgX1OJAAH8"
y.y.y.y - - [20/Jan/2021:10:29:37 -0600] "GET /sonarqube/api/cnesreport/report?key=a.b.c.d%3APROJ1&branch=master&author=Administrator&token=408ca0d72c902d8930fe76257e3da4ddb55563e7&generation=Generate HTTP/1.1" 200 68 "http://x.x.x.x:9200/sonarqube/extension/cnesreport/report" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36" "AXccL5KlPzvgX1OJAAHz"

**Comment by Sancretor** [comment]
Oh OK, now I see.
This is an issue related with the tool not being compatible with SonarQube 8.5.
But you can find some workaround in this comment : https://github.com/cnescatlab/sonar-cnes-report/issues/172#issuecomment-741729099 
It will make most of the plugin work, but there will still be some issues...

As soon as SonarQube 8.x LTS is out, we will work on full compatibility.

**Comment by vhaislshaha** [comment]
Awesome. 

Reports are now working after making change mentioned in  https://github.com/cnescatlab/sonar-cnes-report/issues/172#issuecomment-741729099 

Thank you so much for your help.

**Comment by Sancretor** [comment]
You're welcome !
I will close this issue then.

**Comment by mayar-selim** [comment]
Hi,

I have the same error "{"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}" with Sonarqube version 8.6.0 community edition and I have tried to update the base URL with http://URL and once again with https://URL and the same issue is persisting. Can you help as it's a blocker to me.
