### ISSUE TITLE
[SQ 8.8] An error has occurred. Please contact your administrator

### ISSUE THREAD

**Issue by rebse** [cnescatlab/sonar-cnes-report#211]
Using CNES Report 3.3.1 as **admin** on Sonarqube Enterprise 8.8 / Windows Server 2012 with Apache reverse proxy.
Using the web api from browser works without any problems.

I've read the compatibility matrix but nevertheless i've tried with SQ 8.8 as the new 8.9 LTS version is coming soon.
Please note,  this bug ain't new, noticed it already from the beginning in 2019 with Sonarqube 7.9, see
[https://community.sonarsource.com/t/first-release-cnesreport-3-0-1/13368/17](https://community.sonarsource.com/t/first-release-cnesreport-3-0-1/13368/17) and also with subsequent CNES plugin versions.

Using the plugin out of the box via Web UI More / CNES Report, it doesn't work at all, because it doesn't respect the sonar.core.serverBaseURL setting, means it uses http://localhost:9000 instead - **this should also be fixed**.
After editing the `plugin.defaultHost` property in plugin.properties it takes the right Sonarqube url.
But every project report brings up this error message

`{"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}`

sonar.log has
```
Apr. 09, 2021 12:27:04 NACHM. fr.cnes.sonar.report.ReportCommandLine execute
INFO: SonarQube URL: https://sonarfoo.xxx.xxx-xxx.de
Apr. 09, 2021 12:27:04 NACHM. fr.cnes.sonar.report.providers.SonarQubeInfoProvider getSonarQubeStatus
SEVERE: Impossible to reach SonarQube instance.
fr.cnes.sonar.report.exceptions.SonarQubeException: Impossible to reach SonarQube instance.
	at fr.cnes.sonar.report.providers.RequestManager.get(RequestManager.java:162)
	at fr.cnes.sonar.report.providers.AbstractDataProvider.stringRequest(AbstractDataProvider.java:344)
	at fr.cnes.sonar.report.providers.AbstractDataProvider.request(AbstractDataProvider.java:300)
	at fr.cnes.sonar.report.providers.SonarQubeInfoProvider.getSonarQubeStatus(SonarQubeInfoProvider.java:67)
	at fr.cnes.sonar.report.factory.ServerFactory.create(ServerFactory.java:70)
	at fr.cnes.sonar.report.ReportCommandLine.execute(ReportCommandLine.java:109)
	at fr.cnes.sonar.plugin.ws.ExportTask.handle(ExportTask.java:88)
	at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:110)
	at org.sonar.server.platform.web.WebServiceFilter.doFilter(WebServiceFilter.java:84)
	at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139)
	at org.sonar.server.platform.web.SonarLintConnectionFilter.doFilter(SonarLintConnectionFilter.java:66)
	at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139)
	at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:81)
	at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.CacheControlFilter.doFilter(CacheControlFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:76)
	at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:58)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.RequestIdFilter.doFilter(RequestIdFilter.java:66)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:353)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1629)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Fail to request https://sonarfoo.xxx.xxx-xxx.de/api/system/status
	at org.sonarqube.ws.client.HttpConnector.doCall(HttpConnector.java:176)
	at org.sonarqube.ws.client.HttpConnector.get(HttpConnector.java:112)
	at org.sonarqube.ws.client.HttpConnector.call(HttpConnector.java:99)
	at fr.cnes.sonar.report.providers.RequestManager.get(RequestManager.java:160)
	... 54 more
Caused by: java.io.IOException: Unexpected response code for CONNECT: 403
	at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.java:358)
	at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.java:197)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:145)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at org.sonarqube.ws.client.HttpConnector.doCall(HttpConnector.java:173)
	... 57 more

Apr. 09, 2021 12:27:04 NACHM. fr.cnes.sonar.report.ReportCommandLine execute
INFO: SonarQube online: false
```
proxy log has

```
10.132.111.116 - - [09/Apr/2021:12:27:02 +0200] "GET /js/2.m.634597d6.chunk.js HTTP/1.1" 200 6451 "https://sonarfoo/extension/cnesreport/report" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 Edg/89.0.774.68"
10.132.111.116 - - [09/Apr/2021:12:27:02 +0200] "GET /js/0.m.68841b04.chunk.js HTTP/1.1" 200 16663 "https://sonarfoo/extension/cnesreport/report" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 Edg/89.0.774.68"
10.132.111.116 - - [09/Apr/2021:12:27:02 +0200] "GET /static/cnesreport/report.js HTTP/1.1" 200 3918 "https://sonarfoo/extension/cnesreport/report" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 Edg/89.0.774.68"
10.132.111.116 - - [09/Apr/2021:12:27:02 +0200] "POST /api/user_tokens/revoke HTTP/1.1" 204 - "https://sonarfoo/extension/cnesreport/report" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 Edg/89.0.774.68"
10.132.111.116 - - [09/Apr/2021:12:27:02 +0200] "POST /api/user_tokens/generate HTTP/1.1" 200 128 "https://sonarfoo/extension/cnesreport/report" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 Edg/89.0.774.68"
10.132.111.116 - - [09/Apr/2021:12:27:02 +0200] "GET /api/users/search?q=ap253 HTTP/1.1" 200 940 "https://sonarfoo/extension/cnesreport/report" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 Edg/89.0.774.68"
10.132.111.116 - - [09/Apr/2021:12:27:02 +0200] "GET /api/components/search?qualifiers=TRK&ps=500 HTTP/1.1" 200 5976 "https://sonarfoo/extension/cnesreport/report" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 Edg/89.0.774.68"
10.132.111.116 - - [09/Apr/2021:12:27:02 +0200] "GET /api/components/search?qualifiers=TRK&ps=500&p=1 HTTP/1.1" 200 5976 "https://sonarfoo/extension/cnesreport/report" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 Edg/89.0.774.68"
10.132.111.116 - - [09/Apr/2021:12:27:02 +0200] "GET /api/project_branches/list?project=de.huk.bigdata%3Aconnect-blacklist HTTP/1.1" 200 256 "https://sonarfoo/extension/cnesreport/report" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 Edg/89.0.774.68"
10.132.111.116 - - [09/Apr/2021:12:27:04 +0200] "GET /api/cnesreport/report?key=de.foo.bar%3Aconnect-blacklist&branch=xxx-yyyy&author=Rebhan%2C+Gilbert+-+SomeUserID&token=6264375e7bea5cf9ed6e47ffcfba6a53cbbd1223&generation=Generate HTTP/1.1" 500 79 "https://sonarfoo/extension/cnesreport/report" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 Edg/89.0.774.68"

```

There is a cnes-report token created for my user.

**Comment by Sancretor** [comment]
Hi @rebse 

Thanks a lot for this detailed issue, and sorry for the very old remaining problem...
As promised on SonarSource forum, @ErwanGauduchon will take a close look at it next week if needed.

What I can say now is that we chose to use "localhost" because the plugin is installed inside your SonarQube instance, so it should point in the right direction.
Also, many users have a front reverse proxy which may interfere or block some requests, depending on the user's configuration, and so on. We won't be able to easily debug all reverse proxy configurations of course, so localhost seemed to be a good choice at that time.

Also, we don't have any Windows Server to test it on the same platform, or even an Enterprise version of SonarQube... that's why it's hard for us to investigate without questioning you.

So, I would like to know why "localhost:9000" is not pointing to your SonarQube server on your host machine ?
Do you have any specific configuration that prevents SonarQube from being accessible using localhost ?

Regarding the token issue, we have an opened issue for the 8.9 LTS release here : #210

**Comment by rebse** [comment]
Hi @Sancretor 

localhost:9000 is the default setting, but of course we have another `sonar.core.serverBaseURL` setting for our Enterprise instance.
It should be possible to retrieve and use this setting somehow. But also after editing this url within the plugin jar / plugin.properties it doesn't work as you see.

**Comment by Sancretor** [comment]
Hi @rebse 

Regarding the token issue, this is already a known issue on SonarQube 8.8, so we are working on it.

Currently, to create this URL we retrieve the custom port & context defined in SonarQube configuration.
So we should be able to connect to your server on localhost, whatever port you are using.

The `sonar.core.serverBaseURL` is useful when you try to access the server from outside your host machine. 
Here, the plugin is inside the SonarQube server, so it may be useless to use your external address just to go back to the server.
I tried to set this property and the `localhost:9000` address is still enabled so ...

Which element of `localhost:9000` is not working on your server ?
Is access to localhost blocked by your firewall ?
Or the 9000 port is not the one to use ?

**Comment by Sancretor** [comment]
Hi @rebse 

We recently refactor a lot our code in order to change how the **plugin mode** works in SonarQube 8.9 LTS.
In our "dev" branch, the **plugin mode** now uses internal SonarQube API through SonarSource Java classes.
So now, it automatically uses the SonarQube server configuration to reach the API and retrieve data.

I'm not sure it will fix your issue, but I think it's worth giving a try.
So if you'd like, you could build the plugin from the "dev" branch and try to use it inside your SonarQube.
Don't hesitate to give us some feedback if you'd like.

**Comment by Sancretor** [comment]
Hi @rebse 

Just to let you know that we just released a new version compatible with 8.9 LTS.
We completely changed the way the plugin handles API calls.
It now uses internal SonarQube classes instead of localhost http calls, so it may resolve your issue.

Please let us know if it doesn't.

**Comment by rebse** [comment]
Hi @Sancretor 

the new version works very well now with SQ 8.9.1 :-)
There's only a problem with reports for existing npm projects migrated from SQ 7.9.1, as they have '@' and '/' in their projectkey. (with SQ 8.9.1 those characters are not allowed anymore, project creation will fail), i.e.

```
2021.11.18 11:18:45 ERROR web[AXwrlL07IbjQrKJsAFwI][o.s.s.w.WebServiceEngine] Fail to process request http://127.0.0.1:9000/api/cnesreport/report?key=de.xxx.xxx.xxx%3Aapp-xxx_xxx-xx-xx&branch=master&language=en_US&author=Rebhan%2C+Gilbert+-+xxxx&token=xxx&enableDocx=true&enableMd=true&enableXlsx=true&enableCsv=true&enableConf=true&generation=Generate
java.io.FileNotFoundException: E:\sonarqube-8.9.1.44547\temp\cnesreport13243644347029680918947384193945093\2021-11-18-@app-xxx\xxx-xx-xx-analysis-report.docx (Das System kann den angegebenen Pfad nicht finden)
 at java.base/java.io.FileOutputStream.open0(Native Method)
 at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
 at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
 at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:126)
 at fr.cnes.sonar.report.exporters.docx.DocXExporter.export(DocXExporter.java:179)
 at fr.cnes.sonar.report.factory.ReportFactory.report(ReportFactory.java:113)
 at fr.cnes.sonar.report.ReportCommandLine.execute(ReportCommandLine.java:146)
 at fr.cnes.sonar.plugin.ws.ExportTask.handle(ExportTask.java:181)
 ...
```
But that's not really a problem, as we will do a bulk edit for all those projectkeys containing characters that are
now forbidden with SQ 8.9.1

**Comment by Sancretor** [comment]
Hi @rebse 
I'm really happy to hear that your problem is now solved ! :)
