### ISSUE TITLE
Cannot use the plugin from a computer "java -jar cnes-report.jar ..."

### ISSUE THREAD

**Issue by merouan-khouttoul** [cnescatlab/sonar-cnes-report#262]
#### Describe the bug

The plugin works correctly since IHM Sonarqube "More => CNES Report ..." but i can't use plugin from a computer !

Here are the errors observed :
- The plugin remains blocked in the state "**Detected SonarQube version: XXX**"
![image](https://user-images.githubusercontent.com/79927204/121522945-f173ca00-c9f5-11eb-8c94-e62b49e9035b.png)

- The plugin returns the error code "**[ERROR] Impossible to reach SonarQube instance.**"

![image](https://user-images.githubusercontent.com/79927204/121523346-65ae6d80-c9f6-11eb-8aff-c4f2bceb0c7f.png)

#### To reproduce

Here is my system information to try to reproduce the error :
- OS : Centos 7
- Plugin : Version 3.3.1
- Version server Sonarqube : 7.9.3
- Version JRE : 1.8.0_292

#### Screenshots & log

Log file ".cnesreport"

`➜  log cat cnesreport-0.log
Jun 10, 2021 2:00:21 PM fr.cnes.sonar.report.ReportCommandLine execute
INFO: SonarQube URL: https://XXXXXXXXXXXXXXXXXXXXXXXXXX
Jun 10, 2021 2:00:22 PM fr.cnes.sonar.report.ReportCommandLine execute
INFO: SonarQube online: true
Jun 10, 2021 2:00:22 PM fr.cnes.sonar.report.ReportCommandLine execute
INFO: Detected SonarQube version: 7.9.3
Jun 10, 2021 2:11:03 PM fr.cnes.sonar.report.ReportCommandLine execute
INFO: SonarQube URL: https://XXXXXXXXXXXXXXXXXXXXXXXXXX
Jun 10, 2021 2:11:05 PM fr.cnes.sonar.report.ReportCommandLine execute
INFO: SonarQube online: true
Jun 10, 2021 2:11:05 PM fr.cnes.sonar.report.ReportCommandLine execute
INFO: Detected SonarQube version: 7.9.3
Jun 10, 2021 2:11:09 PM fr.cnes.sonar.report.ReportCommandLine main
SEVERE: Impossible to reach SonarQube instance.
fr.cnes.sonar.report.exceptions.SonarQubeException: Impossible to reach SonarQube instance.
	at fr.cnes.sonar.report.providers.RequestManager.get(RequestManager.java:162)
	at fr.cnes.sonar.report.providers.AbstractDataProvider.stringRequest(AbstractDataProvider.java:344)
	at fr.cnes.sonar.report.providers.AbstractDataProvider.request(AbstractDataProvider.java:300)
	at fr.cnes.sonar.report.providers.QualityProfileProvider.getQualityProfiles(QualityProfileProvider.java:63)
	at fr.cnes.sonar.report.factory.ReportModelFactory.create(ReportModelFactory.java:119)
	at fr.cnes.sonar.report.ReportCommandLine.execute(ReportCommandLine.java:126)
	at fr.cnes.sonar.report.ReportCommandLine.main(ReportCommandLine.java:78)
Caused by: java.lang.IllegalStateException: Fail to request https://XXXXXXXXXXXXXXXXXXXXXXXXXX/api/qualityprofiles/search?projectKey=XXXXXXXXX&organization=default-organization
	at org.sonarqube.ws.client.HttpConnector.doCall(HttpConnector.java:176)
	at org.sonarqube.ws.client.HttpConnector.get(HttpConnector.java:112)
	at org.sonarqube.ws.client.HttpConnector.call(HttpConnector.java:99)
	at fr.cnes.sonar.report.providers.RequestManager.get(RequestManager.java:160)
	... 6 more
Caused by: okhttp3.internal.http2.StreamResetException: stream was reset: PROTOCOL_ERROR
	at okhttp3.internal.http2.Http2Stream.takeResponseHeaders(Http2Stream.java:153)
	at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:120)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at org.sonarqube.ws.client.OkHttpClientBuilder.addUserAgent(OkHttpClientBuilder.java:195)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at org.sonarqube.ws.client.HttpConnector.doCall(HttpConnector.java:173)
	... 9 more

Jun 10, 2021 2:11:15 PM fr.cnes.sonar.report.ReportCommandLine execute
INFO: SonarQube URL: https://XXXXXXXXXXXXXXXXXXXXXXXXXX
Jun 10, 2021 2:11:16 PM fr.cnes.sonar.report.ReportCommandLine execute
INFO: SonarQube online: true
Jun 10, 2021 2:11:16 PM fr.cnes.sonar.report.ReportCommandLine execute
INFO: Detected SonarQube version: 7.9.3
Jun 10, 2021 2:11:29 PM fr.cnes.sonar.report.ReportCommandLine main
SEVERE: Impossible to reach SonarQube instance.
fr.cnes.sonar.report.exceptions.SonarQubeException: Impossible to reach SonarQube instance.
	at fr.cnes.sonar.report.providers.RequestManager.get(RequestManager.java:162)
	at fr.cnes.sonar.report.providers.AbstractDataProvider.stringRequest(AbstractDataProvider.java:344)
	at fr.cnes.sonar.report.providers.AbstractDataProvider.request(AbstractDataProvider.java:300)
	at fr.cnes.sonar.report.providers.QualityProfileProvider.getQualityProfiles(QualityProfileProvider.java:128)
	at fr.cnes.sonar.report.factory.ReportModelFactory.create(ReportModelFactory.java:119)
	at fr.cnes.sonar.report.ReportCommandLine.execute(ReportCommandLine.java:126)
	at fr.cnes.sonar.report.ReportCommandLine.main(ReportCommandLine.java:78)
Caused by: java.lang.IllegalStateException: Fail to request https://XXXXXXXXXXXXXXXXXXXXXXXXXX/api/qualityprofiles/projects?key=XXXXXXX
	at org.sonarqube.ws.client.HttpConnector.doCall(HttpConnector.java:176)
	at org.sonarqube.ws.client.HttpConnector.get(HttpConnector.java:112)
	at org.sonarqube.ws.client.HttpConnector.call(HttpConnector.java:99)
	at fr.cnes.sonar.report.providers.RequestManager.get(RequestManager.java:160)
	... 6 more
Caused by: okhttp3.internal.http2.StreamResetException: stream was reset: PROTOCOL_ERROR
	at okhttp3.internal.http2.Http2Stream.takeResponseHeaders(Http2Stream.java:153)
	at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:120)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at org.sonarqube.ws.client.OkHttpClientBuilder.addUserAgent(OkHttpClientBuilder.java:195)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at org.sonarqube.ws.client.HttpConnector.doCall(HttpConnector.java:173)
	... 9 more

Jun 10, 2021 2:11:33 PM fr.cnes.sonar.report.ReportCommandLine execute
INFO: SonarQube URL: https://XXXXXXXXXXXXXXXXXXXXXXXXXX
Jun 10, 2021 2:11:35 PM fr.cnes.sonar.report.ReportCommandLine execute
INFO: SonarQube online: true
Jun 10, 2021 2:11:35 PM fr.cnes.sonar.report.ReportCommandLine execute
INFO: Detected SonarQube version: 7.9.3
`

Thank you in advance for your reply,

MK

**Comment by Sancretor** [comment]
Hi @merouan-khouttoul 

Thanks for your feedback !

The plugin mode access your SonarQube server from within it, using requests to localhost.
Whereas the standalone mode use an external address to access the SonarQube server.
So, maybe there's a proxy in between that blocks the requests ...?

This other error seems to confirm that :

> Caused by: okhttp3.internal.http2.StreamResetException: stream was reset: PROTOCOL_ERROR

Does the failed request work if you copy/paste it inside a web browser on your computer ?

> Caused by: java.lang.IllegalStateException: Fail to request https://XXXXXXXXXXXXXXXXXXXXXXXXXX/api/qualityprofiles/projects?key=XXXXXXX

**Comment by Sancretor** [comment]
Hi @merouan-khouttoul 
Did you make any progress regarding this issue ?

**Comment by merouan-khouttoul** [comment]
Hi,

I have found an alternative solution. 
I've noticed that version of java **1.8.0.292_b10** was not working correctly, I had to install an older version of java to solve the report generation problem
The version I have installed is Java **1.8.0.191_b12**

Have you ever tried to reproduce error with a version of java 1.8.0.292 ?

**Comment by Sancretor** [comment]
Hi @merouan-khouttoul 
We never tried to use the CNES Report with this specific version of Java, so we never saw this error.
Weird issue but we're glad it is solved !

By the way, version 3.3.1 is the last release for SonarQube 7.9.x LTS, so future versions will only work for SonarQube 8.9.x LTS.

**Comment by Sancretor** [comment]
Hi !
Just to let you know, we released the 4.0.0 version some time ago, with SQ 8.9 compatibility.
We're closing this issue as the problem seems to be solved.
