### ISSUE TITLE
Project is not building using mvn clean package

### ISSUE THREAD

**Issue by maanasa0318** [cnescatlab/sonar-cnes-report#327]
I am trying to build the project my java home and maven home is set.
Apache Maven 3.5.0 
Java version: 11.0.12, vendor: Oracle Corporation
When I tried to build the project (seeing in dev and master branch)  I am getting below error

$ mvn clean package
[INFO] Scanning for projects...
[ERROR] Internal error: java.lang.ArrayIndexOutOfBoundsException: Index 11557 out of bounds for length 8192 -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.ArrayIndexOutOfBoundsException: Index 11557 out of bounds for length 8192
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:122)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

Please advice thank you.

**Comment by Topin2001** [comment]
Without any news, I close this old issue.
If anything similar happens again, we'll re-open it.
