### ISSUE TITLE
Erreur execution plugin CNES_Report SonarQube 8.9.6 LTS

### ISSUE THREAD

**Issue by usinelogicielle** [cnescatlab/sonar-cnes-report#328]
#### Describe the bug

Lorsque l'on demande un rapport avec le plugin sur une branche précise alors que la "MAIN" branch n'a pas d'analyse, on a un plantage.
Il se peut aussi que l'erreur soit à cause d'un quality gate custom.

#### To reproduce

> _Steps to reproduce the behavior._

Avoir un projet SonarQube avec des analyses sur la branche develop. Mais 0 analyse sur la branche master qui est la main branche de sonarQube.
Demander la génération d'un rapport sur la branche develop.

#### Expected behavior

Que le rapport soit généré

#### Screenshots & log
Le résultat : 
![image](https://user-images.githubusercontent.com/73827301/191209905-92ce4b6a-b3f3-49cc-8114-c99f05aa654e.png)

Log administrateur.
<details>
```
INFO: SonarQube online: true
Sep 20, 2022 8:44:30 AM fr.cnes.sonar.report.ReportCommandLine execute
INFO: Detected SonarQube version: 8.9.6.50800
2022.09.20 08:44:32 ERROR web[AYLYs09LmUIBBJLGK1UB][o.s.s.w.WebServiceEngine] Fail to process request http://URL/api/cnesreport/report?key=KEY&branch=develop&language=en_US&author=AUTHOR&token=TOKEN&enableDocx=true&enableMd=true&enableXlsx=true&enableCsv=true&enableConf=true&generation=Generate
java.io.FileNotFoundException: /opt/sonarqube/temp/cnesreport59857881844176112782170558174527317/conf/QUALITY_GATE_WITH_SPACE.json (No such file or directory)
at java.base/java.io.FileOutputStream.open0(Native Method)
at java.base/java.io.FileOutputStream.open(Unknown Source)
at java.base/java.io.FileOutputStream.<init>(Unknown Source)
at java.base/java.io.FileWriter.<init>(Unknown Source)
at fr.cnes.sonar.report.exporters.JsonExporter.export(JsonExporter.java:57)
at fr.cnes.sonar.report.factory.ReportFactory.createConfigurationFiles(ReportFactory.java:176)
at fr.cnes.sonar.report.factory.ReportFactory.report(ReportFactory.java:106)
at fr.cnes.sonar.report.ReportCommandLine.execute(ReportCommandLine.java:147)
at fr.cnes.sonar.plugin.ws.ExportTask.handle(ExportTask.java:183)
at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:110)
at org.sonar.server.platform.web.WebServiceFilter.doFilter(WebServiceFilter.java:84)
at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139)
at org.sonar.server.platform.web.SonarLintConnectionFilter.doFilter(SonarLintConnectionFilter.java:66)
at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139)
at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:108)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:81)
at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:68)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
at org.sonar.server.platform.web.CacheControlFilter.doFilter(CacheControlFilter.java:76)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:76)
at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:58)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
at org.sonar.server.platform.web.RequestIdFilter.doFilter(RequestIdFilter.java:66)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:364)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:624)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1651)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.base/java.lang.Thread.run(Unknown Source)
```
</details>

Le fichier que j'ai remplacé par "QUALITY_GATE_WITH_SPACE" représente un fichier contenant des espace et qui est le nom d'un quality gate custom.
#### User environment 

SonarQube 8.9.6 LTS de Docker

**Comment by louisjdmartin** [comment]
Je n'arrive pas a reproduire le bug sur en environement dockerisé.
J'ai utilisé un docker avec le plugin https://github.com/mc1arke/sonarqube-community-branch-plugin et le cnes-report en 4.1.2 et 4.1.1 pour mes tests.

**Comment by louisjdmartin** [comment]
Le bug est reproduit, il faut ajouter un "/" dans le nom du quality profile.

**Comment by louisjdmartin** [comment]
Bug corrigé dans la release 4.1.3
