### ISSUE TITLE
Don't use env variable SONARQUBE_HOME to create .cnesreport

### ISSUE THREAD

**Issue by Ags-saltillo** [cnescatlab/sonar-cnes-report#329]
#### Describe the bug

Plugin don't use env variable SONARQUBE_HOME and always create directory /home/sonarqube/.cnesreport (perhaps doesn't exist)

#### To reproduce

Deploy SonarQube with different home directory (p.e: /opt/sonarqube)

#### Expected behavior

Plugin must create directory ${SONARQUBE_HOME}/.cnesreport and work with it

#### Screenshots & log

`2022.09.22 11:28:50 INFO  ce[][o.s.s.p.ServerFileSystemImpl] SonarQube home: /opt/sonarqube
2022.09.22 11:28:51 INFO  ce[][o.s.c.c.CePluginRepository] Load plugins
2022.09.22 11:28:52 INFO  ce[][o.s.c.c.ComputeEngineContainerImpl] Running Community edition
2022.09.22 11:28:52 INFO  ce[][o.s.ce.app.CeServer] Compute Engine is operational
2022.09.22 11:28:52 INFO  app[][o.s.a.SchedulerImpl] Process[ce] is up
2022.09.22 11:28:52 INFO  app[][o.s.a.SchedulerImpl] SonarQube is up
Can't load log handler "java.util.logging.FileHandler"
java.nio.file.NoSuchFileException: /home/sonarqube/.cnesreport/log/cnesreport-0.log.lck
java.nio.file.NoSuchFileException: /home/sonarqube/.cnesreport/log/cnesreport-0.log.lck
 at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
 at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
 at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
 at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(Unknown Source)`

#### User environment 

AKS: v1.12.6
SonarQube: 7.9-LTS ( sonarqube:7.9-community )
Sonar CNES Report Plugin: 3.3.1

**Comment by obriat** [comment]
The plugin should check if the directory exists and has correct permissions to write in it.
If not it should try to create it with the correct permissions. If this could not be done, them display a user friendly message and log the error in sonar.log.

If this folder is only used for logging, why not just create a `${SONARQUBE_HOME}/logs/cnesreport.log` file or use the recommended class : [org.sonar.api.utils.log.Logger](https://javadocs.sonarsource.org/latest/org/sonar/api/utils/log/Logger.html) (see https://docs.sonarsource.com/sonarqube/8.9/extension-guide/developing-a-plugin/plugin-basics/#logging) ?

**Comment by ku4eto** [comment]
Getting
`Caused by: java.lang.ExceptionInInitializerError: Exception java.security.AccessControlException: access denied ("java.io.FilePermission" "/opt/sonarqube-9.9.4.87374/.cnesreport" "write") [in thread "http-nio-127.0.0.1-8080-exec-3"]
`
The sonarqube folder is referenced by the main java process with a symlink (/opt/sonarqube > /opt/sonarqube-x.x.x).
Manually creating the file/folder with correct owner and permissions does not solve the issue.
