### ISSUE TITLE
error generating the Cnes report in sonarqube 9.9

### ISSUE THREAD

**Issue by damianwayne7** [cnescatlab/sonar-cnes-report#348]
#### Describe the bug

> I am trying to generate  the cnes report in sonarqube 9.9 and while generating the report i am getting this error
<img width="945" alt="image" src="https://user-images.githubusercontent.com/69078764/221161389-55585877-ae66-44b1-8c69-bf094a5e639f.png">

#### To reproduce

> install sonarqube 9.9 in ubuntu 22 & copy paste the cnes report plugin 4.1.1 jar & restart sonar service || try to generate the report.

#### Expected behavior

> _A clear and concise description of what you expected to happen._

#### Screenshots & log

> 2023.02.24 10:49:09 ERROR web[][o.s.s.p.w.RootFilter] Processing of request /api/cnesreport/report?key=sqp_d89a
1fd0b3a53014a1fb1bd8981db7f927d8d6a2&branch=main&language=en_US&author=Administrator&token=squ_c7263b40952967a0
2eb418cad58ec14633d77622&enableDocx=false&enableMd=false&enableXlsx=true&enableCsv=false&enableConf=false&gener
ation=Generate failed
javax.servlet.ServletException: Could not initialize class fr.cnes.sonar.report.ReportCommandLine
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:334)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:187)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143)
        at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:81)
        at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:68)
        at jdk.internal.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:187)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143)
        at org.sonar.server.platform.web.CspFilter.doFilter(CspFilter.java:63)
        at jdk.internal.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)

#### User environment 

> OS ubuntu 22.04

* OS: [e.g. Windows 10]
* Project version: [e.g. 2.0.0]

**Comment by rayzeinkah** [comment]
Cnes report does not support sonarqube 9.9, there is an open pr for it

**Comment by bientt210** [comment]
I have the same issue when using version 4.2.0 on Sonar 9.9. Does anyone help to resolve it?
