### ISSUE TITLE
Error generating the Cnes report in sonarqube 9.9

### ISSUE THREAD

**Issue by bientt210** [cnescatlab/sonar-cnes-report#355]
#### Describe the bug

<img width="1434" alt="image" src="https://github.com/cnescatlab/sonar-cnes-report/assets/47659964/0c09c824-0df4-4ebb-b06c-5cafbc57fbdd">

#### Screenshots & log

Caused by: java.lang.NoClassDefFoundError: Could not initialize class fr.cnes.sonar.report.ReportCommandLine
        at fr.cnes.sonar.plugin.ws.ExportTask.handle(ExportTask.java:183)
        at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:111)
        at org.sonar.server.platform.web.WebServiceFilter.doFilter(WebServiceFilter.java:84)
        at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:153)
        at org.sonar.server.platform.web.SonarLintConnectionFilter.doFilter(SonarLintConnectionFilter.java:66)
        at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:153)
        at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:116)
        at jdk.internal.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311)
        ... 130 common frames omitted

#### User environment 

* OS: MacOS
* Project version: 

=>> I'm using the latest plugin version 4.2.0. Can anyone help to resolve it? 

Thanks you so much.

**Comment by bientt210** [comment]
Resolved.
