### ISSUE TITLE
Exception in thread "main" java.lang.NumberFormatException: For input string: "AboveAverage.cs"

### ISSUE THREAD

**Issue by difeijin** [cnescatlab/sonar-cnes-report#86]
### Expected behavior
generate report

### Actual behavior
This error happens in `web.log`:
```
2019.09.28 00:03:57 ERROR web[][o.s.s.p.w.RootFilter] Processing of request /api/cnesreport/report?key=aspose.cells.0827&author=Administrator&token=d17e5de54d26dda886e4b4fed6fe2248670aa0d7&generation=Generate failed
javax.servlet.ServletException: Filter execution threw an exception
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:200)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.sonar.server.user.UserSessionFilter.doFilter(UserSessionFilter.java:87)
at org.sonar.server.user.UserSessionFilter.doFilter(UserSessionFilter.java:71)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.sonar.server.platform.web.CacheControlFilter.doFilter(CacheControlFilter.java:76)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:76)
at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:58)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.sonar.server.platform.web.requestid.RequestIdFilter.doFilter(RequestIdFilter.java:63)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.NoClassDefFoundError: org/apache/poi/openxml4j/exceptions/OpenXML4JException
at fr.cnes.sonar.plugin.ws.ExportTask.handle(ExportTask.java:78)
at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:110)
at org.sonar.server.ws.WebServiceFilter.doFilter(WebServiceFilter.java:88)
at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:126)
at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:95)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
... 41 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.poi.openxml4j.exceptions.OpenXML4JException
at org.sonar.classloader.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:41)
at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
... 47 common frames omitted
```

### Steps to reproduce behavior
```
java -jar sonar-cnes-report-3.1.0.jar -t 34ff2992bfa6f79a5118fa6297c15a8c514c23d4 -s http://192.168.1.240:9000 -p  xxxx
```

```
SonarQube URL: http://192.168.1.240:9000
SonarQube online: true
Detected SonarQube version: 7.9.1
Exception in thread "main" java.lang.NumberFormatException: For input string: "AboveAverage.cs"
        at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
        at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
        at java.lang.Double.parseDouble(Unknown Source)
        at java.lang.Double.valueOf(Unknown Source)
        at fr.cnes.sonar.report.providers.ComponentProvider.getMinMetric(ComponentProvider.java:87)
        at fr.cnes.sonar.report.providers.ComponentProvider.getMetricStats(ComponentProvider.java:125)
        at fr.cnes.sonar.report.factory.ReportModelFactory.create(ReportModelFactory.java:101)
        at fr.cnes.sonar.report.ReportCommandLine.execute(ReportCommandLine.java:134)
        at fr.cnes.sonar.report.ReportCommandLine.main(ReportCommandLine.java:77)
```

### Detection version
**cnesreport version:** 3.1.0
**SonarQube version:** 7.9.1

**Comment by begarco** [comment]
Hi @difeijin, 

Please rewrite your issue like in the template we provide.

It seems to be a specific C# plugin related issue(C# metric) , but we need more information about your use case to reproduce it and fix it.

Regards,
Benoît

**Comment by begarco** [comment]
Please use `edit` feature of GitHub issues instead of duplicating them.

**Comment by begarco** [comment]
@difeijin I gather all your information in that issue.

Could you provide us your list of installed plugins and their versions?

**Comment by astrasia** [comment]
I have a similar issue. I don't think it is related to C# as I am using PHP (my guess). The errors line are exact. 

I have very limited plug-ins installed, all are the default from SonarQube installation. CNES is the only plug-in I added.

![2019-10-06_18-22-12](https://user-images.githubusercontent.com/12303230/66267695-d509ac80-e866-11e9-9af9-cdb420e4f0a3.jpg)

**Comment by begarco** [comment]
Hello @astrasia,

Could you send us the content of `404.php`, or a piece of project with which we can reproduce thius error?

Thanks.

**Comment by difeijin** [comment]
AboveAverage.cs  is the first file in name order in my project which has a lot of csharp files.I have try put this file(AboveAverage.cs) into a simple small project. the report can generate successfully.so seems it is not related with the specific file but with the entire project.I cannot find any useful info from /sonarqube-7.9.1/logs/ directory.Do you have the debug version or tell me how to turn on the log info.









------------------ 原始邮件 ------------------
发件人: "Alexis Chatillon"<notifications@github.com>;
发送时间: 2019年10月25日(星期五) 下午3:44
收件人: "lequal/sonar-cnes-report"<sonar-cnes-report@noreply.github.com>;
抄送: "伦文叙"<difeijin@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [lequal/sonar-cnes-report] Exception in thread "main"java.lang.NumberFormatException: For input string: "AboveAverage.cs" (#86)




Hi @astrasia,
 
Just a quick reminder.
 In order to investigate, we really need an example file that triggers this error.
 Thanks !

**Comment by difeijin** [comment]
all the plugin installed.
Chinese Pack 1.29,Findbugs 3.11.0,Git 1.8 (build 1574),GitHub Authentication for SonarQube 1.5 (build 870),JaCoCo 1.0.2 (build 475),LDAP 2.2 (build 608),SAML 2.0 Authentication for SonarQube 1.1.0 (build 181),SonarC# 7.15 (build 8572),SonarCSS 1.1.1 (build 1010),SonarFlex 2.5.1 (build 1831),SonarGo 1.1.1 (build 2000),SonarHTML 3.1 (build 1615),SonarJS 5.2.1 (build 7778),SonarJava 5.14 (build 18788),SonarKotlin 1.5.0 (build 315),SonarPHP 3.2.0.4868,SonarPython 1.14.1 (build 3143),SonarQube CNES Report 3.1.0,SonarRuby 1.5.0 (build 315),SonarScala 1.5.0 (build 315),SonarTS 1.9 (build 3766),SonarVB 7.15 (build 8572),SonarXML 2.0.1 (build 2020),Svn 1.9.0.1295,Xanitizer 2.0.0,
http://192.168.1.240:9000/api/cnesreport/report?key=xxx&author=Administrator&token=xxx&generation=Generate
{"errors":[{"msg":"For input string: \"AboveAverage.cs\""}]}




------------------ 原始邮件 ------------------
发件人: "Benoît Garçon"<notifications@github.com>;
发送时间: 2019年10月7日(星期一) 凌晨0:16
收件人: "lequal/sonar-cnes-report"<sonar-cnes-report@noreply.github.com>;
抄送: "伦文叙"<difeijin@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [lequal/sonar-cnes-report] Exception in thread "main"java.lang.NumberFormatException: For input string: "AboveAverage.cs" (#86)




Hello @astrasia,
 
Could you send us the content of 404.php, or a piece of project with which we can reproduce thius error?
 
Thanks.

**Comment by Eduardx05** [comment]
I reproduce the error.

When we extract the component_tree measures in the Component provider. The getMinMetric and the getMaxMetric try to parse the file name of the component tree to double.

I saw that type of error on files that has numbers on the file name.

404.jsp
3A

1E


I change the next methods:

 private double getMinMetric(String metric){
        double min = Double.MAX_VALUE;
        for(Map c: componentsList){
            final String rawValue = (String)c.get(metric);
            if(rawValue!=null){
                try{
                    min = Math.min(min, Double.valueOf(rawValue));
                }catch(NumberFormatException e){
                    LOGGER.warning(metric +" : "+rawValue+" | Error Min" );
                    min = 0;
                }
                
            }
        }
        return min;
    }

    /**
     * Get max value for a specified metrics
     * */
    private double getMaxMetric(String metric){
        double max = -Double.MAX_VALUE;
        for(Map c: componentsList){
            final String rawValue = (String)c.get(metric);
            if(rawValue!=null){
                

                try{
                    max = Math.max(max, Double.valueOf(rawValue));
                }catch(NumberFormatException e){
                    LOGGER.warning(metric +" : "+rawValue+" | Error Max" );
                    max = 0;
                }
            }
        }
        return max;
    }


And then the reports generated.

**Comment by difeijin** [comment]
thanks,good work,
expect the&nbsp; fix.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Eduardx05"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 中午12:06
收件人:&nbsp;"lequal/sonar-cnes-report"<sonar-cnes-report@noreply.github.com&gt;;
抄送:&nbsp;"伦文叙"<difeijin@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [lequal/sonar-cnes-report] Exception in thread "main" java.lang.NumberFormatException: For input string: "AboveAverage.cs" (#86)





 
I reproduce the error.
 
When we extract the component_tree measures in the Component provider. The getMinMetric and the getMaxMetric try to parse the file name of the component tree to double.
 
I saw that type of error on files that has numbers on the file name.
 
404.jsp
 3A
 
1E
 
I change the next methods:
 
private double getMinMetric(String metric){
 double min = Double.MAX_VALUE;
 for(Map c: componentsList){
 final String rawValue = (String)c.get(metric);
 if(rawValue!=null){
 try{
 min = Math.min(min, Double.valueOf(rawValue));
 }catch(NumberFormatException e){
 LOGGER.warning(metric +" : "+rawValue+" | Error Min" );
 min = 0;
 }
         }     }     return min; } /**  * Get max value for a specified metrics  * */ private double getMaxMetric(String metric){     double max = -Double.MAX_VALUE;     for(Map c: componentsList){         final String rawValue = (String)c.get(metric);         if(rawValue!=null){                          try{                 max = Math.max(max, Double.valueOf(rawValue));             }catch(NumberFormatException e){                 LOGGER.warning(metric +" : "+rawValue+" | Error Max" );                 max = 0;             }         }     }     return max; }  
And then the reports generated.

**Comment by Sancretor** [comment]
Hi @Eduardx05 !

Thanks for your feedback and contribution, we truly appreciate it !
We're also glad you managed to reproduce this error... that was a tricky one.
I can't say when, but be sure I'll look into it as soon as possible.

**Comment by jeritiana** [comment]
I stumbled upon this issue too and I needed badly to generate a report lol

You have to be lucky to reproduce this on your side. It happens inside `src/main/java/fr/cnes/sonar/report/providers/ComponentProvider.java`, when the very first component value used inside `isCountableMetric(String metric)` is actually a valid number.

Here is a typical component and its attributes:
```
{Path=include/fieldbus/488, complexity=0, duplicated_lines_density=0.0, cognitive_complexity=0, ncloc=41, ID=AXTj4p-qHIPsNopKiPtX, comment_lines_density=42.3, Name=488}
```
`488` in this particular case means IEEE-488 or GPIB field bus.

When calling `isCountableMetric("Name")`: the first non-null value is used to detect if the metric is countable, and `NumberUtils.isCreatable("488")` is indeed TRUE!

Then, the metric `Name` is also computed for all components in `getMetricStats()`, calling `getMinMetric(String metric)` and `getMaxMetric(String metric)`, as reported by @Eduardx05, leading to the java.lang.NumberFormatException on all file names and directory names. The suggested fix pointed me to this analysis, but it is too late during the runtime.

Fix idea: exclude known attributes not to be in the computed metrics, such as `Name` or `Path`, not relying on their value. This will give a deterministic behavior, independently from the component order or name.

At least, that's what I found and it works on my setup.

Associated PR #179

**Comment by Sancretor** [comment]
Hi @jeritiana 

Thanks a lot or your contribution !
That was a tricky one indeed. 
We will have a look at your PR as soon as possible, as it would be great to merge it for the next 3.3.0 release.
