### ISSUE TITLE
Unknown URL error sent by SonarQube server (code 404)

### ISSUE THREAD

**Issue by ghost** [cnescatlab/sonar-cnes-report#91]
SonarQube URL: http://localhost:9000
SonarQube online: true
Detected SonarQube version: 7.7.0
[ERROR] Unknown URL error sent by SonarQube server (code 404), please check cnesreport compatibility with your SonarQube server version.

Tested for my sonarqube 7.7 with all cnes 2.x.x & 3.x.x, getting above error

**Comment by begarco** [comment]
Thanks for using the cnesreport.

Could you provide us more information?
+ If you use it as standalone, share us the content of the directory `.cnesreport` which should be created in your home directory at first launch.
+ If you use it as SonarQube plugin, share us the content of the file `web.log` which should be in `${SONAR_HOME}/log/`.

**Remind to anonymize your personnal data before posting them.**

Regards.

**Comment by hermamel** [comment]
Hi begarco,

I have the same failure.

SonarQube URL: http://xxx/sonar
SonarQube online: true
Detected SonarQube version: 6.7.7
[ERROR] Unknown URL error sent by SonarQube server (code 404), please check cnesreport compatibility with your SonarQube server version.

web.log :

2019.10.21 11:41:16 INFO  web[][o.s.s.p.Platform] WebServer is operational
2019.10.21 11:42:26 ERROR web[AW3tsTq2bbf1z3/gAAAg][o.s.s.w.WebServiceEngine] Fail to process request http://xxx/sonar/api/cnesreport/report?key=xxx&author=xxx&token=xxx=Generate
fr.cnes.sonar.report.exceptions.SonarQubeException: Impossible to reach SonarQube instance.
	at fr.cnes.sonar.report.ReportCommandLine.execute(ReportCommandLine.java:120)
	at fr.cnes.sonar.plugin.ws.ExportTask.handle(ExportTask.java:78)
	at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:103)
	at org.sonar.server.ws.WebServiceFilter.doFilter(WebServiceFilter.java:86)
	at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:126)
	at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:95)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.user.UserSessionFilter.doFilter(UserSessionFilter.java:87)
	at org.sonar.server.user.UserSessionFilter.doFilter(UserSessionFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:72)
	at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.requestid.RequestIdFilter.doFilter(RequestIdFilter.java:63)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

regards

**Comment by hermamel** [comment]
Indeed, I almost exclusively use custom quality profile. You have a solution for this issue ?

**Comment by AntonioRGit** [comment]
Hermamel, the quick solution is to switch the specific project you want to generate the report for to the default quality profile then generate the report.  Once you are done, simply move the project back to the custom quality profile. Hope that helps!

**Comment by hermamel** [comment]
Still does not work in plugin mode but works in command line.
That's enough for now.
Thanks.

**Comment by hermamel** [comment]
Hello,

I would like to extract other information from the sonarqube database. Could you tell me if there is a document listing the different information available? And if so, tell me where I can find it there.

Regards

**Comment by Sancretor** [comment]
Hi @dmallarapu, @hermamel , @AntonioRGit,

As this looks worrying, it would be great to know why changing the Quality Profile fix your error.

@hermamel : we don't have any specific documentation regarding sonarqube database here, you should have a look at the official documentation.

**Comment by Sancretor** [comment]
Hi @hermamel !  
  
Unfortunately, we are not able to reproduce this error, even when using a custom Quality Profile.  
Could you please provide the full command line you used ?

**Comment by piercemar** [comment]
Hello,

I had the same issue (3.1.1 against SonarQube 6.7 LTS).
The problem is with escaping of special chars. Replacing randomly spaces and pluses is not enough.
I added proper encoding of String url parameters and everything went fine.
Please find my patch in the attached file.
It is for 3.1.0 codebase but should be easy enough to adapt to master.
[patch.txt](https://github.com/lequal/sonar-cnes-report/files/4461008/patch.txt)

Thanks for your good work. It's a pity that reporting is only part of the Enterprise version in SonarQube

**Comment by Sancretor** [comment]
Hi @piercemar !

Thanks for your feedback and contribution, we appreciate it a lot !
I can't say when, but I'll look into it for sure.
